### ISSUE TITLE
Algorithm IV for p_hat_str

### ISSUE THREAD

**Issue by bbontempo3** [awunderground/math658_project#2]
On page 13, where you calculate “strata_variance,” shouldn’t this expression match the summand of the very first sum in the decomposition of V(p_hat_str) on page 12 – i.e., [(N_h^2)(N_h – 1)(0.25)] / [(N^2)*(N_h – 1)]?

**Comment by bbontempo3** [comment]
But somehow I get the same answer as you even using this latter expression. I doubt that's a coincidence, but still, just to keep it consistent with the decomposed form of the variance you derived on page 12, maybe you could change "strata_variance" to the expression in the comment above.

**Comment by awunderground** [comment]
Are you talking about the R code? Sorry, the page numbers just changed when I added new calculations.

**Comment by bbontempo3** [comment]
Yes, now it's at the very bottom of page 14

**Comment by awunderground** [comment]
Ok, I think this is updated now.

**Comment by bbontempo3** [comment]
Ok, great. I checked the first few "marginal variances" for p_hat, and it looks like your code is working great
